const projects = {
  title: 'Portfolio',
  name: 'projects',
  showAdd: true,
  showSearch: true,
  sideBarItem: {
    icon: 'mdi-firework',
    text: 'Portfolios',
    path: '/content',
    query: { entity: 'projects' },
  },
  breadcrumbs: [
    {
      text: 'Home',
      disabled: false,
      href: '/',
    },
    {
      text: 'Portfolio',
      disabled: true,
    },
  ],
  table: {
    headers: [
      {
        text: 'Serviço',
        value: 'name',
        sortable: true,
        align: 'start',
        slot: false,
      },
      {
        text: 'Descrição',
        value: 'note',
        sortable: true,
        align: 'start',
        slot: false,
      },
      {
        text: 'Ramo',
        value: 'array-ramo',
        externalFont: true,
        externalEntity: 'sections',
        externalLabel: 'name',
        sortable: true,
        align: 'start',
        slot: true,
      },
      {
        text: 'Imagens',
        value: 'file-image',
        sortable: false,
        align: 'start',
        slot: true,
      },
    ],
    search: '',
    itemsPerPage: 15,
    multiSort: true,
    mobileBreakPoint: 900,
    noDataText: 'Sem serviços',
    noResultText: 'Não existe esse serviço',
    dense: false,
  },
  form: [
    {
      key: 'name',
      type: 'textInput',
      label: 'Nome do Projeto',
      rules: [(v) => !!v || 'Nome é obrigatorio'],
      value: '',
    },
    {
      key: 'image',
      type: 'upload',
      label: 'Imagem do Projeto',
      multiple: true,
      extension: '.png, .jpg, .jpeg',
      colorChip: 'orange',
      rules: [(v) => !!v || 'O arquivo é obrigatorio'],
      value: '',
    },
    {
      key: 'note',
      type: 'inputArea',
      label: 'Descrição do serviço',
      rules: [(v) => !!v || 'Descrição é obrigatorio'],
      value: '',
    },
    {
      key: 'ramo',
      type: 'vSelect',
      label: 'selecione a seção',
      isMultiple: true,
      dataCameFromOtside: true,
      dataFont: 'sections',
      dataLabel: 'name',
      rules: [(v) => !!v || 'O ramo é obrigatorio'],
      value: '',
    },
  ],
}

export default projects
